### ISSUE TITLE
Segmentation fault when deriving enum with hex literal

### ISSUE THREAD

**Issue by copy** [whitequark/ppx_deriving#100]
I'm getting a segmentation fault when using merlin on the following test case on 4.03.0+flambda. `ppx_deriving` is the program that segfaults, so I'm assuming the issue belongs here.

```ocaml
type t =
  | A [@value 0x1]
[@@deriving enum]
```

**Comment by whitequark** [comment]
`ppx_deriving` [doesn't use any unsafe code](https://github.com/whitequark/ppx_deriving/search?utf8=%E2%9C%93&q=unsafe) (nor do its dependencies), and safe OCaml code ought to never segfault, so the problem lies elsewhere.

My suspicion would be that there is somehow a mismatch of the OCaml versions ppx_deriving, merlin, and possibly ocamlc are built for, so become absolutely sure that they match properly.

**Comment by copy** [comment]
That makes sense, but I'm only using the latest versions from opam. I also made a clean 4.03 switch and I'm still having this issue.

**Comment by whitequark** [comment]
Ok, can you get me a backtrace with gdb? You may need to recompile everything with `-g` which can be achieved by adding `OCAMLPARAM=_,g` to your environment and rebuilding the switch from scratch.

**Comment by copy** [comment]
Sure.

```
Core was generated by `/home/ant/.opam/4.03.0/lib/ppx_deriving/./ppx_deriving /home/ant/.opam/4.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000698a59 in parse_sign_and_base ()
(gdb) bt
#0  0x0000000000698a59 in parse_sign_and_base ()
#1  0x0000000000698e18 in parse_intnat ()
#2  0x0000000000698f93 in caml_int_of_string ()
#3  0x00000000004b4b42 in camlPpx_deriving__int_1998 () at src/ppx_deriving.cppo.ml:78
#4  0x00000000004b4efc in camlPpx_deriving__get_attr_3021 () at src/ppx_deriving.cppo.ml:119
#5  0x00007fd2d217fa7a in camlPpx_deriving_enum__map_1873 () at src_plugins/ppx_deriving_enum.cppo.ml:26
#6  0x00000000006467c4 in camlList__fold_left_1270 () at list.ml:88
#7  0x00007fd2d21802cc in camlPpx_deriving_enum__mappings_of_type_1871 () at src_plugins/ppx_deriving_enum.cppo.ml:35
#8  0x00007fd2d2180438 in camlPpx_deriving_enum__str_of_type_3893 () at src_plugins/ppx_deriving_enum.cppo.ml:73
#9  0x0000000000646581 in camlList__map_1237 () at list.ml:59
#10 0x00007fd2d2181275 in camlPpx_deriving_enum__fun_4285 () at src_plugins/ppx_deriving_enum.cppo.ml:115
#11 0x00000000004b43a3 in camlPpx_deriving__fun_9452 () at src/ppx_deriving.cppo.ml:388
#12 0x00000000006467c4 in camlList__fold_left_1270 () at list.ml:88
#13 0x00000000004d76a1 in camlAst_helper__with_default_loc_1365 () at parsing/ast_helper.ml:32
#14 0x00000000004b6b95 in camlPpx_deriving__structure_8332 () at src/ppx_deriving.cppo.ml:444
#15 0x00000000005177b7 in camlAst_mapper__implem_2565 () at parsing/ast_mapper.ml:812
#16 0x0000000000517abb in camlAst_mapper__rewrite_2587 () at parsing/ast_mapper.ml:849
#17 0x000000000051ec56 in camlAst_mapper__run_main_2613 () at parsing/ast_mapper.ml:904
#18 0x00000000004b2fe3 in camlPpx_deriving_main__entry () at parsing/ast_mapper.ml:915
#19 0x00000000004af469 in caml_program ()
#20 0x00000000006a9536 in caml_start_program ()
#21 0x00000000006a9b45 in caml_main ()
#22 0x00000000004aeb1c in main ()
```

**Comment by copy** [comment]
Has been confirmed to be a merlin bug on irc:

```
3:15 PM <def`> copy`: merlin doesn't support 4.03, your behavior is "normal"
3:15 PM <def`> fix expected in 10 days
```

**Comment by let-def** [comment]
Yes, this is merlin's fault. Support for 4.03 is not yet there, it is expecting an old version of marshalled files.
